In [1]:
import pandas as pd

# Replace 'your_file.dat' with the path to your .dat file.
# Replace 'your_delimiter' with the delimiter used in your file (e.g., '\t' for tab).
df = pd.read_csv("height.dat",delimiter=' ')

In [120]:
from scipy.stats import skewtest
from scipy.stats import skew

In [13]:
import pandas as pd
from scipy.stats import norm

In [121]:
skew(df)

array([-0.00136114])

In [17]:
count = (df < 4.802).sum()

In [51]:
df.mean()

inches    4.812047
dtype: float64

In [20]:
count/5000

inches    0.002
dtype: float64

In [8]:
from scipy.stats import skewtest

# Assuming your DataFra
skewness_test = skewtest(df)

In [119]:
skewness_test

SkewtestResult(statistic=array([-0.0393515]), pvalue=array([0.96861015]))

In [9]:
p_value = skewness_test.pvalue

In [11]:
p_value

array([0.96861015])

In [74]:
from scipy import stats

# Assuming your DataFrame is named df and the column for height is named 'height'
mean_height = df.mean()
std_dev_height = df.std()
n = len(df)

# Calculate the standard error
se = std_dev_height / (n ** 0.5)

# 95% confidence level
confidence = 0.95
alpha = 1 - confidence

# Degrees of freedom
dfree = n - 1

# t-critical value for 95% confidence
t_critical = stats.t.ppf(1 - alpha / 2, dfree)

# Lower confidence limit of the mean
lower_limit = mean_height - t_critical * se

In [77]:
mean_height

inches    4.812047
dtype: float64

In [76]:
lower_limit

inches    4.81195
dtype: float64

In [73]:
mean_height + t_critical * se

inches    4.812143
dtype: float64

In [79]:
# Sample mean and standard deviation
mean_height = df.mean()
std_dev_height = df.std()

# Sample size
n = len(df)

# Z-score for a 95% confidence interval
z_score = norm.ppf(0.975)  # two-tailed test

# Lower confidence limit
lower_limit = mean_height - z_score * (std_dev_height / (n ** 0.5))


In [81]:
 mean_height + z_score * (std_dev_height / (n ** 0.5))


inches    4.812143
dtype: float64

In [15]:
mean_height = df.mean()
std_dev_height = df.std()

# Calculate the percentage of cans less than 4.802 inches
percentage = norm.cdf(4.802, mean_height, std_dev_height)

In [16]:
percentage

array([0.00197083])

In [4]:
df_defectives = pd.read_csv("defectives.dat",delimiter=' ')

In [5]:
df_defectives

cans
0      1
1      0
2      2
3      2
4      1
..   ...
70     1
71     4
72     2
73     3
74     3

[75 rows x 1 columns]

In [21]:
rate=df_defectives.mean()

In [22]:
rate

cans    1.773333
dtype: float64

In [25]:
from scipy.stats import poisson

In [26]:
prob_more_than_3 = 1 - sum(poisson.pmf(k, rate) for k in range(4))

In [27]:
prob_more_than_3 

array([0.10446218])

In [87]:
df_defectives

cans
0      1
1      0
2      2
3      2
4      1
..   ...
70     1
71     4
72     2
73     3
74     3

[75 rows x 1 columns]

In [107]:
mean_defectives = df_defectives.iloc[:, 0].mean() 

In [108]:
mean_defectives

1.7733333333333334

In [94]:
# Calculate the number of defectives in the dataset
defectives = df_defectives.sum()

# Calculate the sample proportion 𝛑
p_hat = defectives / n

# Calculate the critical value for a 90% confidence level
alpha = 0.10  # 1 - Confidence level
z_critical = stats.norm.ppf(1 - alpha / 2)

# Calculate the lower confidence limit (LCL)
lower_confidence_limit = p_hat - z_critical * ((p_hat * (1 - p_hat)) / n)**0.5
upper_confidence_limit = p_hat + z_critical * ((p_hat * (1 - p_hat)) / n)**0.5

In [95]:
lower_confidence_limit 

cans    0.022857
dtype: float64

In [96]:
upper_confidence_limit

cans    0.030343
dtype: float64

In [106]:
# Set the confidence level
confidence_level = 0.90

# Calculate the critical value (Z)
alpha = 1 - confidence_level
Z = stats.norm.ppf(1 - alpha / 2)

In [105]:
lower=

cans   NaN
dtype: float64

In [31]:
alpha = 1 - confidence_level
Z = stats.norm.ppf(1 - alpha / 2)


In [43]:
mean_defectives-

0.2

In [88]:
df_defects

defects
0         1
1         0
2         1
3         3
4         5
5         3
6         3
7         3
8         6
9         0
10        5
11        1
12        2
13        1
14        0
15        3
16        4
17        3
18        1
19        1
20        4
21        2
22        1
23        0
24        0
25        1
26        0
27        2
28        4
29        3
30        1
31        0
32        0
33        3
34        7
35        1
36        0
37        2
38        4
39        4
40        6
41        4
42        2
43        1
44        3
45        2
46        1
47        0
48        2
49        1

In [44]:
zero_defects_count = (df_defects == 0).sum().sum()
total_cans = df_defects.shape[0]
probability_zero_defects_one_can = zero_defects_count / total_cans

# Calculate the probability for 50 cans
probability_zero_defects_50_cans = probability_zero_defects_one_can ** 50

# Round the result to four decimal places
probability_rounded = round(probability_zero_defects_50_cans, 4)

In [50]:
probability_zero_defects_50_cans

1.1258999068426271e-35

In [114]:
import scipy.stats as st 
import numpy as np
# define sample data 
gfg_data = df_defectives
  
# create 90% confidence interval 
st.t.interval(alpha=0.90, df=len(gfg_data), 
              loc=np.mean(gfg_data), 
              scale=st.sem(gfg_data)) 

/home/jeffwa/anaconda3/envs/DL_new/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/tmp/ipykernel_13312/1856651442.py:7: DeprecationWarning: Use of keyword argument `alpha` for method `interval` is deprecated. Use first positional argument or keyword argument `confidence` instead.
  st.t.interval(alpha=0.90, df=len(gfg_data),


(array([1.5441007]), array([2.00256596]))

In [113]:
len(gfg_data)

75

In [115]:
df_defectives.mean()

cans    1.773333
dtype: float64

In [117]:
import scipy.stats as st 
import numpy as np
# define sample data 
gfg_data = df
  
# create 90% confidence interval 
st.t.interval(alpha=0.95, df=len(gfg_data)-1, 
              loc=np.mean(gfg_data), 
              scale=st.sem(gfg_data)) 

/home/jeffwa/anaconda3/envs/DL_new/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/tmp/ipykernel_13312/962407660.py:7: DeprecationWarning: Use of keyword argument `alpha` for method `interval` is deprecated. Use first positional argument or keyword argument `confidence` instead.
  st.t.interval(alpha=0.95, df=len(gfg_data)-1,


(array([4.81194998]), array([4.81214322]))

In [118]:
st.sem(gfg_data)

array([4.92856683e-05])